### SERVER SIDE ONLY SETTINGS
dbConnStr:
    # admin connection should grant full data modification rights
    admin: "pgsql: "
    # guest connection should be read-only
    guest: "pgsql: "
storage: 
    dir: /home/www-data/data
    tmpDir: /home/www-data/tmp
    # number of binary resources directory storage levels
    # each level corresponds to a two-digit part of the resource id counting from right, e.g.:
    # - id = 1234567 and level = 1 stores a binary in  {dir}/67/1234567
    # - id = 1234567 and level = 2 stores a binary in  {dir}/45/67/1234567
    # - id = 9 and level = 2 store a binary in {dir}/00/09
    levels: 2
    modeDir: 777
    modeFile: 666
    # as accepted by the https://www.php.net/manual/en/function.hash-init.php
    hashAlgorithm: sha1
accessControl:
    adminRoles:
        - admin
    create:
        # who can create new resources
        allowedRoles:
            - creator
        # rights assigned to the creator uppon resource creation
        creatorRights:
            - read
            - write
        # rights assigned to other roles upon resource creation
        assignRoles:
            read: []
    defaultAction:
        read: deny
        write: deny
    enforceOnMetadata: false
    schema:
        read: https://vocabs.acdh.oeaw.ac.at/schema#acl
        write: https://vocabs.acdh.oeaw.ac.at/schema#aclWrite
    db:
        connStr: 'pgsql: '
        table: users
        userCol: user_id
        dataCol: data
    authMethods:
        - class: \zozlak\auth\authMethod\TrustedHeader
          parameters:
            - HTTP_EPPN
        - class: \zozlak\auth\authMethod\HttpBasic
          parameters:
            - repo
        - class: \zozlak\auth\authMethod\Guest
          parameters:
            - public
metadataManagment:
    nonRelationProperties:
        - http://www.w3.org/1999/02/22-rdf-syntax-ns#type
        - https://vocabs.acdh.oeaw.ac.at/schema#hasPid
    autoAddIds:
        # add/skip/deny
        default: add
        addNamespaces: []
        skipNamespaces: 
            - http://127.0.0.1
        denyNamespaces: []
transactionController:
    socket: 
        # unix/inet
        type: unix
        # only for the unix type
        path: /home/www-data/txSocket
        # only for the inet type
        address: ''
        # only for the inet type
        port: 0
    logging:
        file: /home/www-data/log/tx.log
        # debug/info/notice/warning/error/critical/alert/emergency
        level: debug
    # transaction state check interval in ms
    checkInterval: 500
    # transaction timeout in s
    timeout: 15
    # do transactions have to be complete in ACID terms?
    enforceCompleteness: false
fullTextSearch:
    # e.g. "java -Xmx1g -jar ../tika-app.jar --text" or "http://127.0.0.1:12345/"
    tikaLocation: http://127.0.0.1:12345/
    sizeLimits:
        indexing: 1G
        highlighting: 10M
    mimeFilter:
        # skip/include
       type: include
       mime:
           - text/turtle
           - text/xml
    propertyFilter:
        type: skip
        properties: []
metadataManager:
    # triples to be always added
    fixed: []
    # triples to be added when a given property is missing
    default:
        https://vocabs.acdh.oeaw.ac.at/schema#acl:
            - value: public
    forbidden: []
    copying:
        'https://vocabs.acdh.oeaw.ac.at/schema#hasPid': https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
rest:
    logging:
        file: /home/www-data/log/rest.log
        # debug/info/notice/warning/error/critical/alert/emergency
        level: debug
    defaultMime: application/octet-stream
    defaultMetadataFormat: text/turtle
    metadataFormats:
        - text/turtle
        - application/json
        - application/ld+json
        - application/n-triples
        - application/rdf+xml
    # resource/neighbors/relatives
    defaultMetadataReadMode: neighbors
    # add/merge/overwrite (merge is probably the only sane default)
    defaultMetadataWriteMode: merge
    # resource/neighbors/relatives
    defaultMetadataSearchMode: resource
    handlers:
        rabbitMq:
            #host: localhost
            #port: 5672
            #user: guest
            #password: guest
            ## in s
            #timeout: 1
            #exceptionOnTimeout: true
        classLoader:
            #acdhOeaw\acdhRepo\tests: /home/zozlak/roboty/ACDH/repo/rdbms/tests
        methods:
            get:
            create:
                - type: function
                  function: \acdhOeaw\acdhRepo\handler\MetadataManager::manage
                #- type: rpc
                #  queue: onCreateRpc
            delete:
            updateBinary:
                - type: function
                  function: \acdhOeaw\acdhRepo\handler\MetadataManager::manage
            updateMetadata:
                - type: function
                  function: \acdhOeaw\acdhRepo\handler\MetadataManager::manage
            txBegin:
            txCommit:
            txRollback:
            txProlong:
### BOTH SERVER AND CLIENT SIDE CONFIG
    urlBase: http://127.0.0.1
    pathBase: /
    headers:
        metadataReadMode: X-METADATA-READ-MODE
        metadataParentProperty: X-PARENT-PROPERTY
        metadataWriteMode: X-METADATA-WRITE-MODE
        transactionId: X-TRANSACTION-ID
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    delete: delete://delete
    searchMatch: search://match
    searchFts: search://fts
    binarySize: https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize
    fileName: http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#filename
    mime: https://vocabs.acdh.oeaw.ac.at/schema#hasFormat
    hash: http://www.loc.gov/premis/rdf/v1#hasMessageDigest
    modificationDate: http://fedora.info/definitions/v4/repository#lastModified
    modificationUser: http://fedora.info/definitions/v4/repository#lastModifiedBy
    binaryModificationDate: http://binaryModDate
    binaryModificationUser: http://binaryModUser
    creationDate: http://fedora.info/definitions/v4/repository#created
    creationUser: http://fedora.info/definitions/v4/repository#createdBy
### CLIENT-ONLY SETTINGS
    dissService:
        class: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationService
        location: https://vocabs.acdh.oeaw.ac.at/schema#serviceLocation
        returnFormat: https://vocabs.acdh.oeaw.ac.at/schema#hasReturnType
        matchProperty: https://vocabs.acdh.oeaw.ac.at/schema#matchesProp
        matchValue: https://vocabs.acdh.oeaw.ac.at/schema#matchesValue
        matchRequired: https://vocabs.acdh.oeaw.ac.at/schema#isRequired
        revProxy: https://vocabs.acdh.oeaw.ac.at/schema#serviceRevProxy
        parameterClass: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationServiceParameter
        parameterDefaultValue: https://vocabs.acdh.oeaw.ac.at/schema#hasDefaultValue
        parameterRdfProperty: https://vocabs.acdh.oeaw.ac.at/schema#usesRdfProperty
        hasService: https://vocabs.acdh.oeaw.ac.at/schema#hasDissService
    ingest:
        epicPid: https://vocabs.acdh.oeaw.ac.at/schema#hasPid
        idNamespace: https://id.acdh.oeaw.ac.at/
        location: https://vocabs.acdh.oeaw.ac.at/schema#hasLocationPath
        vidNamespace: https://id.acdh.oeaw.ac.at/vid/
        containerDir: /home/zozlak/roboty/ACDH/repo/rdbms-lib-ingest/tests
        containerToUriPrefix: acdhContainer://
        isNewVersion: https://vocabs.acdh.oeaw.ac.at/schema#isNewVersionOf
        isPrevVersion: https://vocabs.acdh.oeaw.ac.at/schema#isPreviousVersionOf
        indexerDefaultBinaryClass: ''
        indexerDefaultCollectionClass: ''
# client library authorization settings
auth:
    httpHeader:
        Eppn: admin
    httpBasic:
        user: ''
        passsword: ''
