schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    delete: delete://delete
    searchMatch: search://match
    searchFts: search://fts
    binarySize: https://vocabs.acdh.oeaw.ac.at/schema#hasRawBinarySize
    fileName: https://vocabs.acdh.oeaw.ac.at/schema#hasFilename
    mime: https://vocabs.acdh.oeaw.ac.at/schema#hasFormat
    hash: https://vocabs.acdh.oeaw.ac.at/schema#hasHash
    modificationDate: https://vocabs.acdh.oeaw.ac.at/schema#updated
    modificationUser: https://vocabs.acdh.oeaw.ac.at/schema#updatedBy
    binaryModificationDate: https://vocabs.acdh.oeaw.ac.at/schema#binaryUpdated
    binaryModificationUser: https://vocabs.acdh.oeaw.ac.at/schema#binaryUpdatedBy
    creationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
    creationUser: https://vocabs.acdh.oeaw.ac.at/schema#createdBy
    # non-repo core mappings
    pid: https://vocabs.acdh.oeaw.ac.at/schema#hasPid
    binarySizeCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize
    hosting: https://vocabs.acdh.oeaw.ac.at/schema#hasHosting
    accessRestriction: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
    accessRole: https://vocabs.acdh.oeaw.ac.at/schema#hasRestrictionRole
    countCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasNumberOfItems
    classes:
        repoObject: https://vocabs.acdh.oeaw.ac.at/schema#RepoObject
        sharedObject: https://vocabs.acdh.oeaw.ac.at/schema#AgentOrPlaceOrPublication
        container: https://vocabs.acdh.oeaw.ac.at/schema#Container
    namespaces:
        ontology: https://vocabs.acdh.oeaw.ac.at/schema#
        id: https://id.acdh.oeaw.ac.at/'
        vid: https://id.acdh.oeaw.ac.at/vid/
    dissService:
        class: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationService
        location: https://vocabs.acdh.oeaw.ac.at/schema#serviceLocation
        returnFormat: https://vocabs.acdh.oeaw.ac.at/schema#hasReturnType
        matchProperty: https://vocabs.acdh.oeaw.ac.at/schema#matchesProp
        matchValue: https://vocabs.acdh.oeaw.ac.at/schema#matchesValue
        matchRequired: https://vocabs.acdh.oeaw.ac.at/schema#isRequired
        revProxy: https://vocabs.acdh.oeaw.ac.at/schema#serviceRevProxy
        parameterClass: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationServiceParameter
        parameterDefaultValue: https://vocabs.acdh.oeaw.ac.at/schema#hasDefaultValue
        parameterRdfProperty: https://vocabs.acdh.oeaw.ac.at/schema#usesRdfProperty
        hasService: https://vocabs.acdh.oeaw.ac.at/schema#hasDissService
    versioning:
        isNewOf: https://vocabs.acdh.oeaw.ac.at/schema#isNewVersionOf
        isPrevOf: https://vocabs.acdh.oeaw.ac.at/schema#isPreviousVersionOf
    ingest:
        location: https://vocabs.acdh.oeaw.ac.at/schema#hasLocationPath
        containerToUriPrefix: acdhContainer://
        defaultBinaryClass: https://vocabs.acdh.oeaw.ac.at/schema#Resource
        defaultCollectionClass: https://vocabs.acdh.oeaw.ac.at/schema#Collection

