rest:
  headers:
    metadataReadMode: X-METADATA-READ-MODE
    metadataParentProperty: X-PARENT-PROPERTY
    metadataWriteMode: X-METADATA-WRITE-MODE
    transactionId: X-TRANSACTION-ID
    withReferences: X-WITH-REFERENCES
    resourceProperties: X-RESOURCE-PROPERTIES
    relativesProperties: X-RELATIVES-PROPERTIES
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    delete: delete://delete
    searchMatch: search://match
    searchOrder: search://order
    searchOrderValue: search://orderValue
    searchFts: search://fts
    searchFtsProperty: search://ftsProperty
    searchCount: search://count
    searchWeight: search://weight
    binarySize: https://vocabs.acdh.oeaw.ac.at/schema#hasRawBinarySize
    fileName: https://vocabs.acdh.oeaw.ac.at/schema#hasFilename
    mime: https://vocabs.acdh.oeaw.ac.at/schema#hasFormat
    hash: https://vocabs.acdh.oeaw.ac.at/schema#hasHash
    modificationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasUpdatedDate
    modificationUser: https://vocabs.acdh.oeaw.ac.at/schema#hasUpdatedRole
    binaryModificationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasBinaryUpdatedDate
    binaryModificationUser: https://vocabs.acdh.oeaw.ac.at/schema#hasBinaryUpdatedRole
    creationDate: https://vocabs.acdh.oeaw.ac.at/schema#hasAvailableDate
    creationUser: https://vocabs.acdh.oeaw.ac.at/schema#createdBy
    # non-repo core mappings
    pid: https://vocabs.acdh.oeaw.ac.at/schema#hasPid
    binarySizeCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasBinarySize
    hosting: https://vocabs.acdh.oeaw.ac.at/schema#hasHosting
    accessRole: https://vocabs.acdh.oeaw.ac.at/schema#hasRestrictionRole
    accessRestriction: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
    accessRestrictionAgg: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestrictionSummary
    license: https://vocabs.acdh.oeaw.ac.at/schema#hasLicense
    licenseAgg: https://vocabs.acdh.oeaw.ac.at/schema#hasLicenseSummary
    countCumulative: https://vocabs.acdh.oeaw.ac.at/schema#hasNumberOfItems
    isNewVersionOf: https://vocabs.acdh.oeaw.ac.at/schema#isNewVersionOf
    cmdiPid: https://vocabs.acdh.oeaw.ac.at/schema#hasMetadataPid
    biblatex: https://vocabs.acdh.oeaw.ac.at/schema#hasCustomCitation
    titleImage: https://vocabs.acdh.oeaw.ac.at/schema#isTitleImageOf
    classes:
        repoObject: https://vocabs.acdh.oeaw.ac.at/schema#RepoObject
        binaryContent: https://vocabs.acdh.oeaw.ac.at/schema#BinaryContent
        sharedObject: https://vocabs.acdh.oeaw.ac.at/schema#AgentOrPlaceOrPublication
        collection: https://vocabs.acdh.oeaw.ac.at/schema#Collection
        topCollection: https://vocabs.acdh.oeaw.ac.at/schema#TopCollection
        project: https://vocabs.acdh.oeaw.ac.at/schema#Project
        resource: https://vocabs.acdh.oeaw.ac.at/schema#Resource
        metadata: https://vocabs.acdh.oeaw.ac.at/schema#Metadata
        image: https://vocabs.acdh.oeaw.ac.at/schema#Image
        publication: https://vocabs.acdh.oeaw.ac.at/schema#Publication
        place: https://vocabs.acdh.oeaw.ac.at/schema#Place
        organisation: https://vocabs.acdh.oeaw.ac.at/schema#Organisation
        person: https://vocabs.acdh.oeaw.ac.at/schema#Person
        agent: https://vocabs.acdh.oeaw.ac.at/schema#Agent
    namespaces:
        ontology: https://vocabs.acdh.oeaw.ac.at/schema#
        id: https://id.acdh.oeaw.ac.at/
        vid: https://id.acdh.oeaw.ac.at/vid/
        cmdi: https://id.acdh.oeaw.ac.at/cmdi/
        ebucore: http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#
        fedora: http://fedora.info/definitions/v4/repository#
        premis: http://www.loc.gov/premis/rdf/v1#
        rdfs: http://www.w3.org/1999/02/22-rdf-syntax-ns#
    dissService:
        class: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationService
        location: https://vocabs.acdh.oeaw.ac.at/schema#serviceLocation
        returnFormat: https://vocabs.acdh.oeaw.ac.at/schema#hasReturnType
        matchProperty: https://vocabs.acdh.oeaw.ac.at/schema#matchesProp
        matchValue: https://vocabs.acdh.oeaw.ac.at/schema#matchesValue
        matchRequired: https://vocabs.acdh.oeaw.ac.at/schema#isRequired
        revProxy: https://vocabs.acdh.oeaw.ac.at/schema#serviceRevProxy
        parameterClass: https://vocabs.acdh.oeaw.ac.at/schema#DisseminationServiceParameter
        parameterDefaultValue: https://vocabs.acdh.oeaw.ac.at/schema#hasDefaultValue
        parameterRdfProperty: https://vocabs.acdh.oeaw.ac.at/schema#usesRdfProperty
        hasService: https://vocabs.acdh.oeaw.ac.at/schema#hasDissService
        parent: https://vocabs.acdh.oeaw.ac.at/schema#relation
    ingest:
        location: https://vocabs.acdh.oeaw.ac.at/schema#hasLocationPath
        containerToUriPrefix: acdhContainer://
        defaultBinaryClass: https://vocabs.acdh.oeaw.ac.at/schema#Resource
        defaultCollectionClass: https://vocabs.acdh.oeaw.ac.at/schema#Collection
    ontology:
        order: https://vocabs.acdh.oeaw.ac.at/schema#ordering
        recommended: https://vocabs.acdh.oeaw.ac.at/schema#recommendedClass
        langTag: https://vocabs.acdh.oeaw.ac.at/schema#langTag
        vocabs: https://vocabs.acdh.oeaw.ac.at/schema#vocabs
        dateStart: https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedStartDate
        dateEnd: https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedEndDate
        url: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
        version: https://vocabs.acdh.oeaw.ac.at/schema#hasVersion
        info: https://vocabs.acdh.oeaw.ac.at/schema#hasVersionInfo
        description: https://vocabs.acdh.oeaw.ac.at/schema#hasDescription

